In [ ]:
import os
import psycopg2
# Provide your Neon connection string
connection_string = "postgresql://rainfall_owner:Ylzg4Fbjs9uh@ep-spring-truth-a1owr4u7.ap-southeast-1.aws.neon.tech/rainfall?sslmode=require"
# Connect using the connection string
connection = psycopg2.connect(connection_string)
# Create a new cursor object
cursor = connection.cursor()

In [ ]:
table_drop_railfall = "DROP TABLE IF EXISTS rainfall"
cursor.execute(table_drop_railfall)
# Commit the changes
connection.commit()

# Create Table

In [ ]:
create_table_sql = '''
  CREATE TABLE IF NOT EXISTS rainfall (
  id BIGSERIAL PRIMARY KEY,
  ProvinceId INTEGER,
  ProvinceName CHAR(60),
  ProvinceName2 CHAR(60),
  MinRain double precision,
  MaxRain double precision,
  AvgRain double precision,
  region CHAR(20),
  Year CHAR(4),
  Month CHAR(2),
  Date DATE,
  Month_TH CHAR(20)
  );
'''

In [ ]:
cursor.execute(create_table_sql)
result = connection.commit()
print(result)

None

# Insert data to Neon

In [ ]:
import pandas as pd
import numpy as np

pd = pd.read_csv("rainfall.csv");

In [ ]:
import datetime

format = '%d/%m/%y'

In [ ]:
pd.head()

,ProvinceID,ProvinceName,ProvinceName 2,MinRain,MaxRain,AvgRain,region,Year,Month,Date,Month_TH
0,10,กรุงเทพมหานคร,Bangkok,54.299999,257.230011,142.119137,กลาง,2018,1,1/1/18,มกราคม
1,11,สมุทรปราการ,Samut Prakan,76.250000,256.100006,137.302046,กลาง,2018,1,1/1/18,มกราคม
2,12,นนทบุรี,Nonthaburi,38.360001,161.470001,113.433771,กลาง,2018,1,1/1/18,มกราคม
3,13,ปทุมธานี,Pathum Thani,51.439999,116.500000,82.901688,กลาง,2018,1,1/1/18,มกราคม
4,14,พระนครศรีอยุธยา,Phra Nakhon Si Ayutthaya,8.850000,88.589996,39.960089,กลาง,2018,1,1/1/18,มกราคม

In [ ]:
for row in pd.iterrows():
  provinceId = row[1]['ProvinceID']
  provinceName = row[1]['ProvinceName']
  provinceNameTh = row[1]['ProvinceName 2']
  minRain = round(row[1]['MinRain'],3)
  maxRain = round(row[1]['MaxRain'],3)
  avgRain = round(row[1]['AvgRain'],3)
  region = row[1]['region']
  year = row[1]['Year']
  month = row[1]['Month']
  date = datetime.datetime.strptime(row[1]['Date'], format).date()
  monthTh = row[1]['Month_TH']

  insert_statement = "INSERT INTO rainfall (ProvinceId,ProvinceName,ProvinceName2,MinRain,MaxRain,AvgRain,region,Year,Month,Date,Month_TH) VALUES (%d, '%s', '%s', %f, %f, %f, '%s', '%s', '%s', '%s', '%s');" % (provinceId, provinceName, provinceNameTh, minRain, maxRain, avgRain, region, year, month, date, monthTh)
  # Execute the SQL statements
  cursor.execute(insert_statement)
  # Commit the changes
  connection.commit()